export enum Department {
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  USER = 'USER',
  SALES = 'SALES',
  WELCOME_CALL = 'WELCOME_CALL',
  PAYMENT_VERIFY = 'PAYMENT_VERIFY',
  VENUE_MANAGER = 'VENUE_MANAGER',
  HR = 'HR',
}
